#!/bin/bash

SECRETS=$(kubectl get secret -o name)

for secret in $SECRETS
do
  secretName=$(echo $secret | cut -f2 -d'/')
  echo "Copying ${secret} to ${secretName}.yaml"
  kubectl get $secret -o yaml | egrep -v "creationTimestamp|namespace:|resourceVersion|selfLink|uid" > ${secretName}.yaml
  echo
done
