#!/bin/bash

function export_object {
    object_type=$1
    objects=$(kubectl get $object_type -o name)
    for object in $objects
    do
        object_name=$(echo $object | cut -f2 -d'/')
        echo "Copying ${object} to ${object_name}.yaml"
        kubectl get $object -o yaml | egrep -v "creationTimestamp|namespace:|resourceVersion|selfLink|uid" > ${object_name}.yaml
        echo
    done
}

command -v kubectl >/dev/null 2>&1 || { echo >&2 "kubectl is required but is not found. Aborting."; exit 1; }

PS3="""
*NOTE* Files will be created in the current working directory
Please select the number of the Kubernetes object type you want to export_object as a yaml file.

Selection: """
     
options=("Pod" "Statefulset" "Deployment" "Replicaset" "Daemonset" "Service" "Secret" "Configmap" "All" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Pod")
            export_object pod
            ;;
        "Statefulset")
            export_object statefulset
            ;;
        "Deployment")
            export_object deployment
            ;;
        "Replicaset")
            export_object replicaset
            ;;
        "Daemonset")
            export_object daemonset
            ;;
        "Service")
            export_object service
            ;;
        "Secret")
            export_object secret
            ;;
        "Configmap")
            export_object configmap
            ;;
        "All")
            echo "*NOTE* 'all' does not include secrets."
            export_object all
            ;;
        "Quit")
            break
            ;;
        *) echo "Invalid option $REPLY";;
    esac
done
